@token_admin = 525db0425781dd94e53bf0a43d4b4b5eb02e532d
@user_token = c28697849b6a525c4daed05eec05f216157d102a

###
// Разное
get http://127.0.0.1/api/


###
// Список пользователей
GET http://127.0.0.1:8000/api/users/ 

###
// Временное
POST http://127.0.0.1:8000/api/auth/token/login/

###
// создание пользователя пользователя
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "vpsdsdupks1111ddn@yandex.ru",
"username": "vasya.pupkin_111134",
"first_name": "Вася_21",
"last_name": "Пупкин",
"password": "Qwerty1232342341"
}

###
// текущий пользователь
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token {{user_token}}

###
// профиль пользователя
GET http://127.0.0.1:8000/api/users/14/


###
// смена пароля
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token {{user_token}}
Content-Type: application/json

{
  "new_password": "_PpJmAMKdsQ1",
  "current_password": "_PpJmAMKdsQ"
}

### 
// создание пользователя с очень длинным именем
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "vpupkin@yandex.ru",
"username": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"first_name": "Вася_2",
"last_name": "Пупкин",
"password": "Qwerty123"
}

###
//  получение токена
POST http://127.0.0.1:8000/api/auth/token/login/ 
Content-Type: application/json

{
    "password": "_PpJmAMKdsQ1",
    "email": "aaa@saf.comdf"
}

//  "auth_token": "ae02e48e566b744c86b984bacf5b7583de34fd57"

###
//  разлогиниться 
POST http://127.0.0.1:8000/api/auth/token/logout/ 
Authorization: Token ae02e48e566b744c86b984bacf5b7583de34fd57


###
//  получение токена администратором
POST http://127.0.0.1:8000/api/auth/token/login/ 
Content-Type: application/json

{
    "password": "300580",
    "email": "androsov.artem.v@gmail.com"
}

//  "auth_token": "525db0425781dd94e53bf0a43d4b4b5eb02e532d"


###
// Список тегов
GET http://127.0.0.1:8000/api/tags/ 

###
// Получение тега
GET http://127.0.0.1:8000/api/tags/1/ 


###
// Список игридиентов
GET http://127.0.0.1:8000/api/ingredients/

###
// Получение игридиента
GET http://127.0.0.1:8000/api/ingredients/1/

###
// Список рецептов
GET http://127.0.0.1:8000/api/recipes/


###
// Создание рецепта
POST http://127.0.0.1:8000/api/recipes/
Authorization: Token {{user_token}}
Content-Type: application/json

{
"ingredients": [
{
  "id": 1,
  "amount": 21
},
{
  "id": 4,
  "amount": 11
}
],
"tags": [
1,
2
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "rfecipe_9",
"text": "stringerer",
"cooking_time": 54
}

###
// получение рецепта
GET http://localhost:8000/api/recipes/12/

###
// редактирование рецепта
PATCH  http://localhost:8000/api/recipes/12/
Authorization: Token {{user_token}}
Content-Type: application/json

{
"ingredients": [
{
  "id": 1,
  "amount": 23
},
{
  "id": 4,
  "amount": 16
}
],
"tags": [
1,
2
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "rfecipe_8",
"text": "stringerer",
"cooking_time": 50
}


### 
// удаление рецепта (ОШИБКА ОТРАБОТАЛ БЕЗ ПРОВЕРКИ ПРАВ)
DELETE  http://localhost:8000/api/recipes/2/


###
// добавление рецепта в список покупок
POST http://localhost:8000/api/recipes/14/shopping_cart/
Authorization: Token {{user_token}}
###
// удаление рецепта из списка покупок
DELETE http://localhost:8000/api/recipes/14/shopping_cart/
Authorization: Token {{user_token}}

###
// Cкчать список покупок
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token {{user_token}}

###
// Список покупок, запрос от неавторизованного пользователся
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
# Authorization: Token {{user_token}}


###
// добавить рецепт в избранное
POST http://localhost:8000/api/recipes/14/favorite/
Authorization: Token {{user_token}}

###
// удалить рецепт из избранного
DELETE http://localhost:8000/api/recipes/14/favorite/
Authorization: Token {{user_token}}