###
// Разное
get http://127.0.0.1:8000/api/


###
// Список пользователей
GET http://127.0.0.1:8000/api/users/ 
Authorization: Token f2bb7fe545653e86ae7178b6b6d3239cd2addade
###
// создание пользователя пользователя
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "vpupkin@yandex.ru",
"username": "vasya.pupkin_2",
"first_name": "Вася_2",
"last_name": "Пупкин",
"password": "Qwerty123"
}


### 
// создание пользователя с очень длинным именем
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "vpupkin@yandex.ru",
"username": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"first_name": "Вася_2",
"last_name": "Пупкин",
"password": "Qwerty123"
}

###
//  получение токена
POST http://127.0.0.1:8000/api/auth/token/login/ 
Content-Type: application/json

{
    "password": "_PpJmAMKdsQ",
    "email": "aaa@saf.comdf"
}

// bob_12 "auth_token": "f2bb7fe545653e86ae7178b6b6d3239cd2addade"

// artem "auth_token": "61a6b7cca0fb4a7ed869a6565571fda373111bfa"
