@token_admin = a5f4c755d774de4627a189388f641d4e0c00e6db
@user_token = a74a6e12fceba11b6f35bd2e0d18fceddbd93a51

@host = 127.0.0.1:8000
# @host = 127.0.0.1

###
// Разное
get http://{{host}}/api/


###
// Список пользователей
GET http://{{host}}/api/users/ 

###
// Временное
POST http://{{host}}/api/auth/token/login/

###
// создание пользователя пользователя
POST http://{{host}}/api/users/
Content-Type: application/json

{
"email": "vpsdsdupks1111ddn@yandex.ru",
"username": "vasya.pupkin_111134",
"first_name": "Вася_21",
"last_name": "Пупкин",
"password": "Qwerty1232342341"
}

###
// текущий пользователь
GET http://{{host}}/api/users/me/
Authorization: Token {{user_token}}

###
// профиль пользователя
GET http://{{host}}/api/users/14/


###
// смена пароля
POST http://{{host}}/api/users/set_password/
Authorization: Token {{user_token}}
Content-Type: application/json

{
  "new_password": "_PpJmAMKdsQ1",
  "current_password": "_PpJmAMKdsQ"
}

### 
// создание пользователя 
POST http://{{host}}/api/users/
Content-Type: application/json

{
"email": "user_1@yandex.ru",
"username": "User_1",
"first_name": "User",
"last_name": "LastUser",
"password": "Qwerty123"
}

###
//  получение токена
POST http://{{host}}/api/auth/token/login/ 
Content-Type: application/json

{
    "password": "300580",
    "email": "androsov.aretm.v@gmail.com"
}

//  "auth_token": "ae02e48e566b744c86b984bacf5b7583de34fd57"

###
//  разлогиниться 
POST http://{{host}}/api/auth/token/logout/ 
Authorization: Token ae02e48e566b744c86b984bacf5b7583de34fd57


###
//  получение токена администратором
POST http://{{host}}/api/auth/token/login/ 
Content-Type: application/json

{
    "password": "300580",
    "email": "androsov.artem.v@gmail.com"
}

//  "auth_token": "525db0425781dd94e53bf0a43d4b4b5eb02e532d"


###
// Список тегов
GET http://{{host}}/api/tags/ 

###
// Создание тега (для тестов)
POST http://{{host}}/api/tags/ 
Content-Type: application/json

{
  "name": "Не завтрак",
  "color": "#FBCEB1",
  "slug": "nobreakfast"
}

###
// Получение тега
GET http://{{host}}/api/tags/1/ 

###
// Список рецептов
GET http://{{host}}/api/recipes/


###
// Создание рецепта
POST http://{{host}}/api/recipes/
Authorization: Token {{token_admin}}
Content-Type: application/json

{
"ingredients": [
{
  "id": 1,
  "amount": 111
},
{
  "id": 6,
  "amount": 17
}
],
"tags": [
1,
2
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "rfecipe_3",
"text": "stringerer",
"cooking_time": 54
}

###
// получение рецепта
GET http://{{host}}/api/recipes/12/

###
// редактирование рецепта
PATCH  http://{{host}}/api/recipes/12/
Authorization: Token {{user_token}}
Content-Type: application/json

{
"ingredients": [
{
  "id": 1,
  "amount": 23
},
{
  "id": 4,
  "amount": 16
}
],
"tags": [
1,
2
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "rfecipe_8",
"text": "stringerer",
"cooking_time": 50
}


### 
// удаление рецепта (ОШИБКА ОТРАБОТАЛ БЕЗ ПРОВЕРКИ ПРАВ)
DELETE  http://{{host}}/api/recipes/2/


###
// добавление рецепта в список покупок
POST http://{{host}}/api/recipes/2/shopping_cart/
Authorization: Token {{user_token}}
###
// удаление рецепта из списка покупок
DELETE http://{{host}}/api/recipes/14/shopping_cart/
Authorization: Token {{user_token}}

###
// Cкчать список покупок
GET http://{{host}}/api/recipes/download_shopping_cart/
Authorization: Token {{user_token}}

###
// Список покупок, запрос от неавторизованного пользователся
GET http://{{host}}/api/recipes/download_shopping_cart/
# Authorization: Token {{user_token}}


###
// добавить рецепт в избранное
POST http://{{host}}/api/recipes/4/favorite/
Authorization: Token {{user_token}}

###
// удалить рецепт из избранного
DELETE http://{{host}}/api/recipes/14/favorite/
Authorization: Token {{user_token}}

###
// мои подписки
GET http://{{host}}/api/users/subscriptions/
Authorization: Token {{user_token}}

###
// подписаться на пользователя
POST http://{{host}}/api/users/1/subscribe/
Authorization: Token {{user_token}}

###
// отписаться от пользователя
DELETE http://{{host}}/api/users/30/subscribe/
Authorization: Token {{user_token}}

###
// Список игридиентов
GET http://{{host}}/api/ingredients/

###
// Получение игридиента
GET http://{{host}}/api/ingredients/1/

###
GET  http://{{host}}/api/users/subscriptions/?page=1&limit=2&recipes_limit=2
Authorization: Token {{user_token}}