# Generated by Django 3.2 on 2023-04-28 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230427_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe_ingredient',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
