# Generated by Django 3.2 on 2023-04-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230430_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unmeasurement_unit',
            new_name='measurement_unit',
        ),
    ]
