# Generated by Django 3.2 on 2023-04-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_unmeasurement_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
