# Generated by Django 3.2 on 2023-05-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230501_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipe_ingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='pub_date',
        ),
    ]
