# Generated by Django 3.2 on 2023-05-08 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20230508_0402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCard',
            new_name='ShopCart',
        ),
    ]
